# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\x06Number\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\x0c\"M\n\x0fNumberWithToken\x12\x1d\n\x06number\x18\x01 \x01(\x0b\x32\r.proto.Number\x12\x1b\n\x05token\x18\x02 \x01(\x0b\x32\x0c.proto.Token\"\x1c\n\x0cJSONResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1b\n\nFloatScore\x12\r\n\x05score\x18\x01 \x01(\x01\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\xed\x03\n\x0b\x43oreManager\x12>\n\rGetTopArtists\x12\x16.proto.NumberWithToken\x1a\x13.proto.JSONResponse\"\x00\x12<\n\x0bGetTopSongs\x12\x16.proto.NumberWithToken\x1a\x13.proto.JSONResponse\"\x00\x12\x33\n\x0cGetTopGenres\x12\x0c.proto.Token\x1a\x13.proto.JSONResponse\"\x00\x12\x44\n\x13GetRecommendedSongs\x12\x16.proto.NumberWithToken\x1a\x13.proto.JSONResponse\"\x00\x12\x41\n\x17MakeRecommendedPlaylist\x12\x0c.proto.Token\x1a\x16.google.protobuf.Empty\"\x00\x12\x37\n\x12GetPopularityScore\x12\x0c.proto.Token\x1a\x11.proto.FloatScore\"\x00\x12\x34\n\x14GetTopArtistsCollage\x12\x0c.proto.Token\x1a\x0c.proto.Image\"\x00\x12\x33\n\x13GetTopAlbumsCollage\x12\x0c.proto.Token\x1a\x0c.proto.Image\"\x00\x42\x31Z/github.com/anyuan-chen/record/proto/pkg/core_pbb\x06proto3')



_NUMBER = DESCRIPTOR.message_types_by_name['Number']
_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_NUMBERWITHTOKEN = DESCRIPTOR.message_types_by_name['NumberWithToken']
_JSONRESPONSE = DESCRIPTOR.message_types_by_name['JSONResponse']
_FLOATSCORE = DESCRIPTOR.message_types_by_name['FloatScore']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:proto.Number)
  })
_sym_db.RegisterMessage(Number)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:proto.Token)
  })
_sym_db.RegisterMessage(Token)

NumberWithToken = _reflection.GeneratedProtocolMessageType('NumberWithToken', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERWITHTOKEN,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:proto.NumberWithToken)
  })
_sym_db.RegisterMessage(NumberWithToken)

JSONResponse = _reflection.GeneratedProtocolMessageType('JSONResponse', (_message.Message,), {
  'DESCRIPTOR' : _JSONRESPONSE,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:proto.JSONResponse)
  })
_sym_db.RegisterMessage(JSONResponse)

FloatScore = _reflection.GeneratedProtocolMessageType('FloatScore', (_message.Message,), {
  'DESCRIPTOR' : _FLOATSCORE,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:proto.FloatScore)
  })
_sym_db.RegisterMessage(FloatScore)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'core_pb2'
  # @@protoc_insertion_point(class_scope:proto.Image)
  })
_sym_db.RegisterMessage(Image)

_COREMANAGER = DESCRIPTOR.services_by_name['CoreManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/anyuan-chen/record/proto/pkg/core_pb'
  _NUMBER._serialized_start=50
  _NUMBER._serialized_end=74
  _TOKEN._serialized_start=76
  _TOKEN._serialized_end=98
  _NUMBERWITHTOKEN._serialized_start=100
  _NUMBERWITHTOKEN._serialized_end=177
  _JSONRESPONSE._serialized_start=179
  _JSONRESPONSE._serialized_end=207
  _FLOATSCORE._serialized_start=209
  _FLOATSCORE._serialized_end=236
  _IMAGE._serialized_start=238
  _IMAGE._serialized_end=260
  _COREMANAGER._serialized_start=263
  _COREMANAGER._serialized_end=756
# @@protoc_insertion_point(module_scope)
