# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_processing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\x12\x05proto\"\x18\n\x06Images\x12\x0e\n\x06images\x18\x01 \x01(\x0c\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\x32r\n\x0eImageProcessor\x12/\n\x10GetArtistCollage\x12\r.proto.Images\x1a\x0c.proto.Image\x12/\n\x10GetAlbumsCollage\x12\r.proto.Images\x1a\x0c.proto.Imageb\x06proto3')



_IMAGES = DESCRIPTOR.message_types_by_name['Images']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Images = _reflection.GeneratedProtocolMessageType('Images', (_message.Message,), {
  'DESCRIPTOR' : _IMAGES,
  '__module__' : 'image_processing_pb2'
  # @@protoc_insertion_point(class_scope:proto.Images)
  })
_sym_db.RegisterMessage(Images)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_processing_pb2'
  # @@protoc_insertion_point(class_scope:proto.Image)
  })
_sym_db.RegisterMessage(Image)

_IMAGEPROCESSOR = DESCRIPTOR.services_by_name['ImageProcessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGES._serialized_start=33
  _IMAGES._serialized_end=57
  _IMAGE._serialized_start=59
  _IMAGE._serialized_end=81
  _IMAGEPROCESSOR._serialized_start=83
  _IMAGEPROCESSOR._serialized_end=197
# @@protoc_insertion_point(module_scope)
