# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_processing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\x12\x05proto\"a\n\x06Images\x12\x1f\n\x06images\x18\x01 \x03(\x0b\x32\x0f.proto.ImageURL\x12\x10\n\x08rowCount\x18\x02 \x01(\x03\x12\x10\n\x08\x63olCount\x18\x03 \x01(\x03\x12\x12\n\ntargetSize\x18\x04 \x01(\x03\"\x1c\n\x08ImageURL\x12\x10\n\x08imageURL\x18\x01 \x01(\t\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x0c\x32;\n\x0eImageProcessor\x12)\n\nGetCollage\x12\r.proto.Images\x1a\x0c.proto.Imageb\x06proto3')



_IMAGES = DESCRIPTOR.message_types_by_name['Images']
_IMAGEURL = DESCRIPTOR.message_types_by_name['ImageURL']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
Images = _reflection.GeneratedProtocolMessageType('Images', (_message.Message,), {
  'DESCRIPTOR' : _IMAGES,
  '__module__' : 'image_processing_pb2'
  # @@protoc_insertion_point(class_scope:proto.Images)
  })
_sym_db.RegisterMessage(Images)

ImageURL = _reflection.GeneratedProtocolMessageType('ImageURL', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEURL,
  '__module__' : 'image_processing_pb2'
  # @@protoc_insertion_point(class_scope:proto.ImageURL)
  })
_sym_db.RegisterMessage(ImageURL)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_processing_pb2'
  # @@protoc_insertion_point(class_scope:proto.Image)
  })
_sym_db.RegisterMessage(Image)

_IMAGEPROCESSOR = DESCRIPTOR.services_by_name['ImageProcessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGES._serialized_start=33
  _IMAGES._serialized_end=130
  _IMAGEURL._serialized_start=132
  _IMAGEURL._serialized_end=160
  _IMAGE._serialized_start=162
  _IMAGE._serialized_end=184
  _IMAGEPROCESSOR._serialized_start=186
  _IMAGEPROCESSOR._serialized_end=245
# @@protoc_insertion_point(module_scope)
